general {
    colors = true
    interval = 5
}

order += "disk /"
order += "disk /home"
order += "cpu_usage"
order += "memory"
order += "tztime local"

disk "/" {
    format = "/ : %avail"
}
disk "/home" {
    format = "home : %avail"
}
cpu_usage {
    format = "CPU : %usage"
}
memory {
    format = "RAM : %used / %total"
}
tztime local {
    format = "%d/%m/%Y %H:%M"
}
